name: Deploy to Firebase Hosting

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          VERSION="${GITHUB_REF_NAME}"
          sed -i "s/__VERSION__/${VERSION}/g" index.html
          mkdir -p public
          cp -v *.html public/
          cp -v *.css public/
          cp -v *.wav public/
          cp -v *.svg public/
          cp firebase-config.js public/firebase-config.js

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MINIGAME_EB7A7 }}
          projectId: minigame-eb7a7
          channelId: live
